--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Farmero14000/Kits
build-by-default: true
branches:
- main
projects:
  Kits:
    path: ""
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
...
